export const delegaciones = [
    "--Seleccione Delegacion--",
    "Delegacion Departamental La Plata",
    "Delegacion Departamental Azul",
    "Delegacion Departamental Bahia Blanca",
    "Delegacion Departamental Dolores",
    "Delegacion Departamental Exaltacion de la Cruz",
    "Delegacion Departamental Junin",
    "Delegacion Departamental La Matanza",
    "Delegacion Departamental Lomas de Zamora",
    "Delegacion Departamental Mar del Plata",
    "Delegacion Departamental Mercedes",
    "Delegacion Departamental Moron",
    "Delegacion Departamental Necochea",
    "Delegacion Departamental Pergamino",
    "Delegacion Departamental Pilar",
    "Delegacion Departamental Pinamar",
    "Delegacion Departamental Quilmes",
    "Delegacion Departamental San Isidro",
    "Delegacion Departamental San Martin",
    "Delegacion Departamental San Nicolas",
    "Delegacion Departamental Trenque Lauquen",
    "Delegacion Departamental Zarate",
    "Subdelegacion Departamental Tandil",
    "Subdelegacion Departamental Olavarria",
    "Subdelegacion Departamental Tres Arroyos",
    "Subdelegacion Departamental Cañuelas",
    "Subdelegacion Departamental San Vicente",
    "Subdelegacion Departamental Tres de Febrero",
    "Direccion Reunion de Informacion"
]