export const localidades = {
  "La Costa": [
    "San Clemente",
    "Las Toninas",
    "Santa Teresita",
    "Mar del Tuyú",
    "Costa del Este",
    "Aguas Verdes",
    "La Lucila",
    "San Bernardo",
  ],
  "General Lavalle": ["General Lavalle", "Las Chacras", "Paraje Pavon"],
  "General Madariaga": ["General Madariaga"],
  "Pinamar": ["Pinamar", "Valeria del Mar", "Ostende", "Carilò"],
  "Villa Gesell": ["Villa Gesell", "Mar de Las Pampas", "Mar Azul"],
  "Almirante Brown": [
    "Burzaco",
    "Adrogue",
    "Rafael Calzada",
    "San Francisco Solano",
    "Jose Marmol",
    "Claypole",
    "Don Orione",
    "Logchamps",
    "Glew",
    "San Jose",
    "Ministro Rivadavia",
    "Malvinas Argentinas",
  ],
  "Lanus": [
    "Gerli",
    "Lanus Este",
    "Lanus Oeste",
    "Remedios de Escalada",
    "Monte Chingolo",
    "Valentin Alsina",
  ],
  "Avellaneda": [
    "Avellaneda",
    "Gerli",
    "Piñeyro",
    "Dock Sud",
    "Wilde",
    "Sarandi",
  ],
  "Lomas de Zamora": [
    "Banfield",
    "Temperley",
    "Turdera",
    "Llavallol",
    "Villa Fiorito",
    "Ingeniero Budge",
    "Parque Baron",
    "San Jose",
    "Lomas de Zamora",
  ],
  "Ezeiza": [
    "Ezeiza",
    "Tristan Suarez",
    "La Union",
    "Carlos Spegazzini",
    "Canning",
    "El Trebol",
    "Aeropuerto Internacional Ezeiza",
  ],
  "Esteban Echeverría": [
    "Monte Grande",
    "Canning",
    "Luis Guillon",
    "El Jagüel",
    "9 de Abril",
  ],
  "La Matanza": [
    "20 de Junio",
    "Aldo Bonzi",
    "Ciudad Evita",
    "Gonzalez Catan",
    "Gregorio de Laferrere",
    "Isidro Casanova",
    "La Tablada",
    "Lomas del Mirador",
    "Rafael Castillo",
    "Ramos Mejia",
    "San Justo",
    "Tapiales",
    "Villa Luzuriaga",
    "Villa Madero",
    "Virrey del Pino",
  ],
  "Pilar": [
    "Pilar",
    "Pilar Sur",
    "Champagnat",
    "Del Viso",
    "Fatima",
    "Manuel Alberti",
    "Manzanares",
    "San Francisco",
    "Manzone",
    "Pte Derqui",
    "Villa Astolfi",
    "Zelaya",
    "Villa Rosa",
    "La Lonja",
    "Luis Lagomarsino",
  ],
  "General Pueyrredón": ["Mar del Plata", "Batán"],
  "General Alvarado": [
    "Miramar",
    "Comandante Nicanor Otamendi",
    "Mar del Sur",
    "Mechongué",
  ],
  "Mar Chiquita": [
    "Mar Chiquita",
    "Coronel Vidal",
    "Santa Clara del Mar",
    "Vivoratá",
    "General Pirán",
  ],
  "Balcarce": ["Balcarce", "San Agustín", "Los Pinos"],
  "Adolfo Alsina": [
    "Carhue",
    "Rivera",
    "Villa Maza",
    "San Miguel Arcangel",
    "Esteban Agustin Gascon",
  ],
  "Carlos Casares": [
    "Carlos Casares",
    "Smith",
    "Moctezuma",
    "Ordoqui",
    "Hortencia",
    "Bellocq",
    "Cadret",
  ],
  "Carlos Tejedor": [
    "Carlos Tejedor",
    "Tres Algarrobos",
    "Colonia Sere",
    "Timote",
    "Curaru",
  ],
  "Daireaux": ["Daireaux", "Salazar", "Arboledas"],
  "Hipolito Yrigoyen": ["Henderson", "Herreras Vegas"],
  "Rivadavia": [
    "America",
    "Gonzalez Moreno",
    "Fortin Olavarria",
    "Sansinena",
    "Roosevelt",
  ],
  "General Villegas": [
    "General Villegas",
    "Banderalo",
    "Emilio V. Bunge",
    "Cañada Seca",
    "Coronel Charlone",
    "Piedritas",
    "Villa Seboya",
    "Santa Eleodora",
    "Santa Regina",
    "Villa Sauze",
  ],
  "Guamini": [
    "Guamini",
    "Garre",
    "Laguna Alsina",
    "Bonifacio",
    "Arroyo Venado",
    "Cochico",
  ],
  "Pehuajo": [
    "Pehuajo",
    "Juan Jose Paso",
    "Francisco Madero",
    "Nueva Plata",
    "Mones Cazon",
    "Chiclana",
    "Guanaco",
    "Magdala",
    "Girondo",
  ],
  "Pellegrini": ["Pellegrini", "Bocayuva", "De Bary"],
  "Trenque Lauquen": [
    "Trenque Lauquen",
    "Beruti",
    "Garre",
    "Girodias",
    "30 de Agosto",
  ],
  "Tres Lomas": ["Tres Lomas", "Ingeniero Thompson"],
  "Salliquelo": ["Salliquelo", "Quenuma"],
  "Vicente López": [
    "Carapachay",
    "Florida",
    "Florida Oeste",
    "La Lucila",
    "Munro",
    "Olivos",
    "Vicente López",
    "Villa Martelli",
    "Villa Adelina",
  ],
  "San Isidro": [
    "Boulogne Sur Mer",
    "Acassuso",
    "Villa Adelina",
    "Martínez",
    "San Isidro",
    "Béccar",
  ],
  "San Fernando": ["San Fernando", "Victoria", "Virreyes", "Islas"],
  "Tigre": [
    "Tigre",
    "Don Torcuato",
    "Ricardo Rojas",
    "El Talar",
    "General Pacheco",
    "Benavídez",
    "Los Troncos del Talar",
    "Rincón de Milberg",
    "Dique Lújan",
    "Islas",
  ],
  "Castelli": [
    "Castelli",
    "Centro Guerrero (Pueblo Nuevo)",
    "Cerro de la Gloria",
  ],
  "Chascomús": ["Chascomús"],
  "Dolores": ["Dolores", "Sevigné"],
  "General Belgrano": ["General Belgrano", "Gorchs"],
  "General Guido": ["General Guido", "Labardén"],
  "Lezama": ["Lezama"],
  "Maipú": ["Maipú", "Las Armas", "Santo Domingo"],
  "Pila": ["Pila", "Casalins"],
  "Tordillo": ["General Conesa", "Villa Roch"],
  "General San Martín": [
    "Villa Ballester",
    "José León Suárez",
    "Villa Lynch",
    "San Martín",
    "Loma Hermosa",
  ],
  "San Miguel": [
    "Ciudad Santa María",
    "San Miguel",
    "Bella Vista",
    "Campo de Mayo",
  ],
  "Malvinas Argentinas": [
    "Los Polvorines",
    "Villa de Mayo",
    "Adolfo Sourdeaux",
    "Grand Bourg",
    "Tortuguitas",
    "Tierras Altas",
    "Ingeniero Pablo Nogués",
  ],
  "José C. Paz": ["José C. Paz"],
  "Morón": [
    "Moron",
    "Haedo",
    "Castelar",
    "Gervasio Pavon",
    "Villa Sarmiento",
    "El Palomar",
  ],
  "Merlo": [
    "Merlo",
    "San Antonio de Padua",
    "Parque San Martin",
    "Libertad",
    "Pontevedra",
    "Mariano Acosta",
  ],
  "Ituzaingó": ["Ituzaingo", "Villa Ariza", "Las Cabañas", "San Alberrto"],
  "Hurlingham": ["Hurlingham", "Villa Tesei", "Villa Mitre"],
  "Pergamino": [
    "Acevedo",
    "Mariano Hermenegildo Alfonso",
    "Fontezuela",
    "Guerrico",
    "La Violeta",
    "Pergamino",
    "Manuel Ocampo",
    "El Socorro",
    "Juan Andrés de la Peña",
    "Villa San José",
    "Francisco Ayerza",
    "Mariano Benitez",
    "Ortiz Basualdo",
    "Pinzon",
    "Rancagua",
    "Urquiza",
  ],
  "Rojas": [
    "Carabelas",
    "Guido Spano",
    "Hunter",
    "La Beba",
    "Sol de Mayo",
    "Villa Manuel Pomar",
    "Rojas",
    "Rafael Obligado",
    "Los Indios",
    "Roberto Cano",
  ],
  "Salto": [
    "Arroyo Dulce",
    "Berdier",
    "Coronel Isleño",
    "Gahan",
    "Salto",
    "Ines Indart",
    "La Invencible",
    "Tucuarí",
  ],
  "Colón": ["El Arbolito", "Colón", "Pearson", "Sarasa"],
  "Exaltación de la Cruz": [
    "Capilla del Señor",
    "Los Cardales",
    "Pavon - Arroyo de la Cruz - P. Orlando",
    "P. Robles - El Remanso - Etchegoyen",
    "P. la Lata - La Loma",
    "Diego Gaynor",
    "Gob. Andonaegui - Chenaut",
  ],
  "Moreno": [
    "Moreno Cabecera",
    "La Reja",
    "Francisco Alvarez",
    "Cuartel V",
    "Trujui",
    "Paso del Rey",
  ],
  "Luján": [
    "Olivera",
    "Jauregui",
    "Pueblo Nuevo",
    "Cortinez",
    "Open Door",
    "Torres",
    "Carlos Keen",
  ],
  "Gral. Rodriguez": ["General Rodriguez", "Las Malvinas"],
  "Marcos Paz": [
    "Marcos Paz Cabecera",
    "Elias Romero",
    "Santa Rosa",
    "Lisandro de la Torre",
    "Santa Marta",
  ],
  "Gral. Las Heras": [
    "Gral. Las Heras Cabecera",
    "Villars",
    "General Los Hornos",
    "Plomer",
    "La Choza",
    "Lozano",
    "Enrique Fynn",
  ],
  "Tandil": [
    "Tandil",
    "Maria Ignacia Vela",
    "Gardey",
    "De la Canal",
    "Desvio Aguirre",
    "Fulton",
    "La Pastora",
    "Cerro Leones",
    "Iraola",
    "Azucena",
    "La Numancia",
  ],
  "Benito Juarez": [
    "Benito Juarez",
    "Villa Cacique",
    "Barker",
    "Coronel Bunge",
    "Estacion Mariano Roldan",
    "Estacion Gaviña",
    "Estacion Lopez",
    "Tedin Uriburu",
  ],
  "Rauch": ["Rauch", "Miranda", "Egaña", "Colman"],
  "Ayacucho": [
    "Ayacucho",
    "Cangallo",
    "Udaquiola",
    "Langueyu",
    "Fair",
    "Solanet",
    "La Constancia",
    "San Ignacio",
  ],
  "Olavarria": [
    "Sierras Bayas",
    "Sierra Chica",
    "Loma Negra",
    "Hinojo",
    "Colonia San Miguel",
    "Santa Luisa",
    "Blanca Grande",
    "Durañona",
    "Iturregui",
    "Muñoz",
    "Rocha",
    "Mapis",
    "Pourtalé",
    "Recalde",
    "Espigas",
    "Colonia Hinojo",
    "Colonia Nievas",
  ],
  "San Carlos de Bolivar": [
    "Hale",
    "Pirovano",
    "Urdampilleta",
    "Ibarra",
    "Villa Lych Pueyrredon",
    "Miramar",
    "Villa Sanz",
    "Unzué",
  ],
  "Laprida": ["San Jorge", "Pueblo Nuevo"],
  "General Lamadrid": ["Libano", "Las Martinetas", "Colina", "Pontaut"],
  "Azul": ["Chillar", "Cachari", "Pablo Acosta", "Paraje Ariel"],
  "Las Flores": ["Pardo", "El Trigo", "Coronel Boerr", "Rosas"],
  "Tapalque": ["Crotto", "Velloso", "Covello", "Emma"],
  "General Alvear": ["El Parche", "Micheo"],
  "Lincoln": [
    "Lincoln",
    "Roberts",
    "El Triunfo",
    "Arenaza",
    "Martinez de Hoz",
    "Pasteur",
    "Bayauca",
    "Las Toscas",
  ],
  "Gral. Viamonte": ["Los Toldos", "Baigorrita", "Zavalia", "San Emilio"],
  "Gral. Arenales": [
    "Gral. Arenales",
    "Ferre",
    "Ascension",
    "Arribeños",
    "La Angelita",
  ],
  "Leandro N. Alem": [
    "Leandro N. Alem",
    "Vedia",
    "Juan B. Alberdi",
    "El Dorado",
    "Fortin Acha",
  ],
  "Gral. Pinto": ["Gral. Pinto", "Germania", "Cnel. Granada", "Iriarte"],
  "F. Ameghino": ["F. Ameghino", "Blaquier", "El Porvenir"],
  "Presidente Peron": ["Guernica"],
  "San Vicente": ["Alejandro Korn", "San Vicente", "Domselaar"],
  "Brandsen": [
    "Brandsen",
    "Jeppener",
    "Samborombon",
    "Altamirano",
    "Gomez",
    "Oliden",
  ],
  "General Paz": ["Ranchos", "Loma Verde", "Villanueva", "Alegre"],
  "Cañuelas": [
    "Cañuelas",
    "Uribelarrea",
    "Gobernador Udaondo",
    "Vicente Casares",
    "Máximo Paz",
    "Alejandro Petión",
    "Santa Rosa",
  ],
  "Lobos": [
    "Lobos",
    "Empalme Lobos",
    "Zapiola",
    "Salvador María",
    "Antonio Carboni",
    "Elvira",
    "Las Chacras",
    "José Santos Arévalo",
    "Villa Logüercio",
  ],
  "San Miguel del Monte": [
    "San Miguel del Monte",
    "Abbot",
    "Zenon Videla Dorna",
    "Francisco A. Berra",
  ],
  "Roque Pérez": ["Roque Pérez", "Carlos Beguerie"],
  "Saladillo": [
    "Saladillo",
    "Del Carril",
    "Polvaredas",
    "Cazón",
    "Álvarez de Toledo",
    "Juan José Blaquier",
  ],
  "La Plata": [
    "Abasto",
    "Altos de San Lorenzo",
    "Angel Etcheverry",
    "Arturo Seguí",
    "Arana",
    "City Bell",
    "El Peligro",
    "Ignacio Correa",
    "Joaquín Gorina",
    "José Hernández",
    "José Melchor Romero",
    "Lisandro Olmos",
    "Manuel B. Gonnet",
    "Ringelet",
    "Tolosa",
    "San Carlos",
    "Villa Elisa",
    "Villa Elvira",
    "Villa Garibaldi",
  ],
  "Berisso": ["Los Talas", "El Carmen", "Villa Arguello"],
  "Ensenada": ["Punta Lara", "El Dique"],
  "Mercedes": [
    "Altamira",
    "Goldney",
    "Gowland",
    "J.M. García",
    "La Verde",
    "Tomás Jofré",
  ],
  "Navarro": ["Navarro", "Villa Moll", "Las Marianas", "Juan José Almeyra"],
  "Veinticinco de Mayo": [
    "25 de Mayo",
    "Norberto de la Riestra",
    "Pedernales",
    "Del Valle",
    "Gobernador Ugarte",
    "Valdés",
    "San Enrique",
    "Agustín Mosconi",
    "Ernestina",
    "Lucas Monteverde",
  ],
  "San Andrés de Giles": [
    "San Andrés de Giles",
    "Solís",
    "Villa Ruiz",
    "Cucullú",
    "Azcuénaga",
    "Villa Espil",
    "Franklin",
  ],
  "San Antonio de Areco": [
    "San Antonio de Areco",
    "Villa Lía",
    "Duggan",
    "Vagues",
  ],
  "Carmen de Areco": ["Carmen de Areco", "Tres Sargentos", "Gouin"],
  "Necochea": [
    "Necochea",
    "Quequén",
    "Juan N. Fernandez",
    "Nicanor Olivera (La Dulce)",
    "Claraz",
    "Energía",
    "Ramón Santamarina",
  ],
  "Loberia": [
    "Lobería",
    "San Manuel",
    "Tamangueyú",
    "Licenciado Matienzo",
    "Pieres",
    "Arenas Verdes",
  ],
  "San Cayetano": ["San Cayetano", "Ochandío", "Balneario San Cayetano"],
  "San Nicolás": [
    "San Nicolás de los Arroyos",
    "La Emilia",
    "Campo Salles",
    "General Rojo",
    "Conesa",
    "Erezcano",
  ],
  "Ramallo": [
    "Ramallo",
    "Villa Ramallo",
    "Perez Millan",
    "El Paraiso",
    "Villa General Savio",
  ],
  "San Pedro": [
    "San Pedro",
    "Rio Tala",
    "Gobernador Castro",
    "Vuelta de Obligado",
    "Pueblo Doyle",
    "Santa Lucia",
  ],
  "Baradero": ["Baradero", "Alsina", "Santa Coloma", "Irineo Portela"],
  "Arrecifes": ["Arrecifes", "Todd", "Viña"],
  "Capitán Sarmiento": ["Capitán Sarmiento", "La Luisa"],
  "Patagones": [
    "Carmen de Patagones",
    "Cardenal Cagliero",
    "Jose Benito Casas",
    "Bahia San Blas",
    "Stroeder",
    "Villalonga",
    "Villa Balnearia 7 de Marzo",
    "Balneario Los Pocitos",
    "Juan A. Pradere",
  ],
  "Villarino": [
    "Juan Couste",
    "Medanos",
    "Chasicó",
    "Argerich",
    "La Mascota",
    "Teniente Origone",
    "Mayor Buratovich",
    "Hilario Ascasubi",
    "Pedro Luro",
    "Colonia San Adolfo",
    "Balneario La Chiquita",
    "Lago Parque La Salada",
  ],
  "Bahia Blanca": [
    "Bahia Blanca",
    "General Daniel Cerri",
    "Ingeniero White",
    "Cabildo",
  ],
  "Monte Hermoso": ["Monte Hermoso", "Sauce Grande"],
  "Coronel Rosales": [
    "Punta Alta",
    "Pehuen-Co",
    "Bajo Hondo",
    "Villa del Mar",
    "Villa Arias",
    "Sierra de la Ventana",
    "Saldungaray",
  ],
  "Tornquist": [
    "Villa Ventana",
    "Chasicó",
    "Tres Picos",
    "Villa Serrana Las Grutas",
    "Santa Trinidad",
    "San Jose",
    "Santa Maria",
  ],
  "Coronel Suarez": [
    "Huanguelen",
    "Pasman",
    "Cura Malal",
    "Villa La Arcadia",
    "Indio Rico",
    "Lartigau",
  ],
  "Coronel Pringles": [
    "El Pensamiento",
    "El Divisorio",
    "Pigüe",
    "Espartillar",
  ],
  "Saavedra": ["Goyena", "Arroyo Corto", "Dufaur", "Colonia San Martin"],
  "Puan": [
    "Azopardo",
    "Bordenave",
    "Darregueira",
    "Diecisiete de Agosto",
    "Erize",
    "Felipe Sola",
    "Lopez Lecube",
    "San German",
    "Villa Iris",
  ],
  "Adolfo Gonzales Chaves": [
    "Adolfo Gonzales Chaves",
    "De la Garma",
    "Juan Eulogio Barra",
    "Vazquez",
  ],
  "Coronel Dorrego": [
    "Oriente",
    "El Perdido",
    "Aparicio",
    "San Roman",
    "Balneario Marisol",
    "Irene",
    "Faro",
  ],
  "Tres Arroyos": [
    "Tres Arroyos",
    "Claromeco",
    "Orense",
    "Copetonas",
    "Micaela Cascallares",
    "San Francisco de Bellocq",
    "Reta",
    "Balneario Orense",
    "San Mayol",
    "Lin Calel",
    "Barrow",
  ],
  "Castelli": [
    "Castelli",
    "Centro Guerrero (Pueblo Nuevo)",
    "Cerro de la Gloria",
  ],
  "Chascomús": ["Chascomús"],
  "Dolores": ["Dolores", "Sevigné"],
  "Gral. Belgrano": ["General Belgrano", "Gorchs"],
  "General Guido": ["General Guido", "Labardén"],
  "Lezama": ["Lezama"],
  "Maipú": ["Maipú", "Las Armas", "Santo Domingo"],
  "Pila": ["Pila", "Casalins"],
  "Tordillo": ["General Conesa", "Villa Roch"],
  "Campana": [
    "Campana",
    "Altos Los Cardales",
    "Lomas del Rio Lujan",
    "Ingeniero Romulo Otamendi",
  ],
  "Escobar": [
    "Belen de Escobar",
    "Ingeniero Maschwitz",
    "Maquinista Savio",
    "Matheu",
    "Garin",
    "Loma Verde",
  ],
  "Zarate": ["Zarate", "Lima", "Escalada"],
};

export const partidos = Object.keys(localidades).sort();